default['nephology']['server']['repo'] = 'https://github.com/dreamhost/nephology-server-perl.git'
default['nephology']['server']['ref'] = 'HEAD'
default['nephology']['ssh_key_file'] = '/etc/nephology/nephology.ssh'
default['nephology']['mirror_addr'] = 'mirrors.dreamcompute.com'
default['nephology']['boot_initrd'] = 'http://objects.dreamhost.com/public-github/centos6-dhc-v1.0.cpio.gz'
default['nephology']['boot_kernel'] = 'http://objects.dreamhost.com/public-github/vmlinuz-2.6.32-279.11.1.el6.x86_64'
